<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.goedegep.org/poi" nsPrefix="poi">
  <eClassifiers xsi:type="ecore:EClass" name="POIIconResourceDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//POICategoryId"
        defaultValueLiteral="Default POI" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconFileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="POICategoryId">
    <eLiterals name="AMUSEMENT" literal="Amusement"/>
    <eLiterals name="AUTOMOBILE_CLUB" value="1" literal="Automobile club"/>
    <eLiterals name="BANK" value="2" literal="Bank"/>
    <eLiterals name="BORDER_CROSSING" value="3" literal="Border crossing"/>
    <eLiterals name="BOWLING_CENTER" value="4" literal="Bowling center"/>
    <eLiterals name="BUS_STATION" value="5" literal="Bus station"/>
    <eLiterals name="CAMPING" value="6" literal="Camping"/>
    <eLiterals name="CAR_RENTAL" value="7" literal="Car rental"/>
    <eLiterals name="CAR_REPAIR" value="8" literal="Car repair"/>
    <eLiterals name="CASINO" value="9" literal="Casino"/>
    <eLiterals name="CHURCH" value="10" literal="Church"/>
    <eLiterals name="CITY_CENTER" value="11" literal="City center"/>
    <eLiterals name="CINEMA" value="12" literal="Cinema"/>
    <eLiterals name="COMMUNITY_BUILDING" value="13" literal="Community building"/>
    <eLiterals name="EXHIBITION_CENTER" value="14" literal="Exhibition center"/>
    <eLiterals name="FERRY" value="15" literal="Ferry"/>
    <eLiterals name="FIRE_DEPARTMENT" value="16" literal="Fire department"/>
    <eLiterals name="GOLF_COURSE" value="17" literal="Golf course"/>
    <eLiterals name="HOSPITAL" value="18" literal="Hospital"/>
    <eLiterals name="HOTEL" value="19" literal="Hotel"/>
    <eLiterals name="ICE_SKATING_RING" value="20" literal="Ice skating ring"/>
    <eLiterals name="INDUSTRY" value="21" literal="Industry"/>
    <eLiterals name="LEARNING" value="22" literal="Learning"/>
    <eLiterals name="LIBRARY" value="23" literal="Library"/>
    <eLiterals name="MARINA" value="24" literal="Marina"/>
    <eLiterals name="MONUMENT" value="25" literal="Monument"/>
    <eLiterals name="MOTORCYCLE_SERVICE" value="26" literal="Motorcycle service"/>
    <eLiterals name="MUNICIPALITY" value="27" literal="Municipality"/>
    <eLiterals name="MUSEUM" value="28" literal="Museum"/>
    <eLiterals name="NIGHTLIFE" value="29" literal="Nightlife"/>
    <eLiterals name="PARK" value="30" literal="Park"/>
    <eLiterals name="PARK_AND_RIDE" value="31" literal="Park and Ride"/>
    <eLiterals name="PARKING" value="32" literal="Parking"/>
    <eLiterals name="PETROL_STATION" value="33" literal="Petrol station"/>
    <eLiterals name="PHARMACY" value="34" literal="Pharmacy"/>
    <eLiterals name="AIRPORT" value="35" literal="Airport"/>
    <eLiterals name="ATM" value="36"/>
    <eLiterals name="DEFAULT_POI" value="37" literal="Default POI"/>
    <eLiterals name="SKI_RESORT" value="38" literal="Ski resort"/>
    <eLiterals name="POLICE" value="39" literal="Police"/>
    <eLiterals name="POST_OFFICE" value="40" literal="Post office"/>
    <eLiterals name="RAILWAY_STATION" value="41" literal="Railway station"/>
    <eLiterals name="REST_AREA" value="42" literal="Rest area"/>
    <eLiterals name="RESTAURANT" value="43" literal="Restaurant"/>
    <eLiterals name="SHOPPING_CENTER" value="44" literal="Shopping center"/>
    <eLiterals name="SHOP" value="45" literal="Shop"/>
    <eLiterals name="SPORT" value="46" literal="Sport"/>
    <eLiterals name="THEATER" value="47" literal="Theater"/>
    <eLiterals name="TOURIST_INFORMATION" value="48" literal="Tourist information"/>
    <eLiterals name="TOURIST_ATTRACTION" value="49" literal="Tourist attraction"/>
    <eLiterals name="WINERY" value="50" literal="Winery"/>
    <eLiterals name="SNORKELING_LOCATION" value="51" literal="Snorkeling location"/>
    <eLiterals name="HOME" value="52" literal="Home"/>
    <eLiterals name="BED_AND_BREAKFAST" value="53" literal="Bed and Breakfast"/>
    <eLiterals name="SCENIC_VIEWPOINT" value="54" literal="Scenic viewpoint"/>
    <eLiterals name="LODGE" value="55" literal="Lodge"/>
    <eLiterals name="CAR_WASH" value="56" literal="Car wash"/>
    <eLiterals name="CONVENTION_CENTER" value="57" literal="Convention center"/>
    <eLiterals name="CONVENIENCE_STORE" value="58" literal="Convenience store"/>
    <eLiterals name="EMERGENCY" value="59" literal="Emergency"/>
    <eLiterals name="GOVERMENT" value="60" literal="Goverment"/>
    <eLiterals name="GUESTHOUSE" value="61" literal="Guesthouse"/>
    <eLiterals name="BAR" value="62" literal="Bar"/>
    <eLiterals name="RECREATION" value="63" literal="Recreation"/>
    <eLiterals name="YOUTH_HOSTEL" value="64" literal="Youth hostel"/>
    <eLiterals name="CITY" value="65" literal="City"/>
    <eLiterals name="MOUNTAIN" value="66" literal="Mountain"/>
    <eLiterals name="BEACH" value="67" literal="Beach"/>
    <eLiterals name="CAVE" value="68" literal="Cave"/>
    <eLiterals name="MEMORIAL" value="69" literal="Memorial"/>
    <eLiterals name="SQUARE" value="70" literal="Square"/>
    <eLiterals name="CASTLE" value="71" literal="Castle"/>
    <eLiterals name="BRIDGE" value="72" literal="Bridge"/>
    <eLiterals name="NEIGHBOURHOOD" value="73" literal="Neighbourhood"/>
    <eLiterals name="AQUADUCT" value="74" literal="Aquaduct"/>
    <eLiterals name="BUILDING" value="75" literal="Building"/>
    <eLiterals name="LAKE" value="76" literal="Lake"/>
    <eLiterals name="CANYON" value="77" literal="Canyon"/>
    <eLiterals name="LANDSCAPE" value="78" literal="Landscape"/>
    <eLiterals name="MOUNTAIN_PASS" value="79" literal="Mountain pass"/>
    <eLiterals name="HIKING" value="80" literal="Hiking"/>
    <eLiterals name="GLACIER" value="81" literal="Glacier"/>
    <eLiterals name="WATERFALL" value="82" literal="Waterfall"/>
    <eLiterals name="SWIMMING_POOL" value="83" literal="Swimming pool"/>
    <eLiterals name="MARKET" value="84" literal="Market"/>
    <eLiterals name="BUS_STOP" value="85" literal="Bus stop"/>
    <eLiterals name="ZOO" value="86" literal="Zoo"/>
    <eLiterals name="ISLAND" value="87" literal="Island"/>
    <eLiterals name="CABLE_CAR" value="88" literal="Cable car"/>
    <eLiterals name="CAFE" value="89" literal="Cafe"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="POIIconResourceInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="poiIconResourceDescriptors"
        upperBound="-1" eType="#//POIIconResourceDescriptor" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
