<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://goedegep.vacations/model" nsPrefix="vacations">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Een vakantie is een Event, waarbij de 'date' de vertrekdatum is.&#xD;&#xA;De 'notes' bevatten de algemene informatie over de vakantie."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Vacations">
    <eOperations name="findVacation" eType="#//Vacation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Find a vacation that started on a specific date and with a specific title."/>
      </eAnnotations>
      <eParameters name="date" eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EFlexDate"/>
      <eParameters name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addVacation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Add a vacation to the vacations. The vacation must have &lt;b>date&lt;/b> set, as the vacations are ordered by date.&#xD;&#xA;&#xD;&#xA;@param vacation the vacation to be added to the vacations."/>
      </eAnnotations>
      <eParameters name="vacation" eType="#//Vacation"/>
    </eOperations>
    <eOperations name="findVacation" eType="#//Vacation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Find a vacation that started on a specific date and with a specific title."/>
      </eAnnotations>
      <eParameters name="date" eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EFlexDate"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vacations" upperBound="-1"
        eType="#//Vacation" unsettable="true" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The vacations should be ordered by date, latest date first. When a vacation is added via the method addVacation(), the vacation is automatically added at the right location.&#xD;&#xA;However when you add a vacation via the method getVacations().add(vacation), you have to take care of the order yourself."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="home" eType="#//Location"
        unsettable="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tips" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vacation" eSuperTypes="../../goedegep.types.model/model/types.ecore#//Event">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A vacation may have been at a single location. In this case fill in 'location'. Fill in 'bezochteLocaties' for any location visited.&lt;br/>&#xD;&#xA;If you stayed at different locations, you can mix the locations where you stayed with the visited places, all in 'bezochteLocaties'.&#xD;&#xA;"/>
    </eAnnotations>
    <eOperations name="findDocument" eType="ecore:EClass ../../goedegep.types.model/model/types.ecore#//FileReference">
      <eParameters name="documentPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getAllFileReferences" ordered="false" upperBound="-1" eType="ecore:EClass ../../goedegep.types.model/model/types.ecore#//FileReference">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method returns all file references (as FileReference) of the vacation. This means all documents of the vacation and all pictures of all Locations."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAllReferencedFiles" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method returns all referenced files (as String) of the vacation. This means all  'Bestand' attributes  of the documents of the vacation and all pictures of all Locations."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getDayNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject">
      <eParameters name="vacationElement" eType="#//VacationElement"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EFlexDate"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documents" upperBound="-1"
        eType="ecore:EClass ../../goedegep.types.model/model/types.ecore#//FileReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pictures" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//VacationElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="#//VacationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationType" eType="ecore:EEnum ../../goedegep.poi.model/model/POI.ecore#//POICategoryId"
        defaultValueLiteral="Default POI" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="houseNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webSite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="#//ActivityLabel"
        defaultValueLiteral="UNSPECIFIED" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EFlexDate"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EFlexDate"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundingbox" eType="#//BoundingBox"
        unsettable="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundaries" upperBound="-1"
        eType="#//Boundary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VacationElement" abstract="true">
    <eOperations name="getDayNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get the day number to which this element belongs.&#xD;&#xA;The day number is the sum of all 'days' of all VacationElementDay's up until this element."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getVacation" eType="#//Vacation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get the Vacation to which this element belongs."/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//VacationElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActivityLabel">
    <eLiterals name="VERBLIJF" literal="Verblijf"/>
    <eLiterals name="WANDELING" value="1" literal="Wandeling"/>
    <eLiterals name="HEENREIS" value="2" literal="Heenreis"/>
    <eLiterals name="TERUGREIS" value="3" literal="Terugreis"/>
    <eLiterals name="HUURAUTO_OPHALEN" value="4" literal="Huurauto ophalen"/>
    <eLiterals name="HUURAUTO_WEGBRENGEN" value="5" literal="Huurauto wegbrengen"/>
    <eLiterals name="UNSPECIFIED" value="6"/>
    <eLiterals name="AUTORIT" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//VacationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Day" eSuperTypes="#//VacationElement">
    <eOperations name="getDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="days" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="1" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Picture" eSuperTypes="#//VacationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictureReference" eType="ecore:EClass ../../goedegep.types.model/model/types.ecore#//FileReference"
        unsettable="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GPXTrack" eSuperTypes="#//VacationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trackReference" eType="ecore:EClass ../../goedegep.types.model/model/types.ecore#//FileReference"
        unsettable="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoundingBox">
    <eOperations name="isValid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="west" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DoubleObject"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="north" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DoubleObject"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="east" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DoubleObject"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="south" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DoubleObject"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boundary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" upperBound="-1"
        eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EWGS84Coordinates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapImage" eSuperTypes="#//VacationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imageReference" eType="ecore:EClass ../../goedegep.types.model/model/types.ecore#//FileReference"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
