<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http:///goedegep.configuration/model" nsPrefix="configuration">
  <eClassifiers xsi:type="ecore:EClass" name="Look">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class specifies visual aspects of the GUI components of an application. Currently only colors are specified.&#xD;&#xA;&#xD;&#xA;backgroundColor&#xD;&#xA;General background color, e.g. used for panels, panes, layouts.&#xD;&#xA;&#xD;&#xA;buttonBackgroundColor&#xD;&#xA;Buttons use a gradient, so ...&#xD;&#xA;&#xD;&#xA;panelBackgroundColor&#xD;&#xA;Already covered by backgroundColor&#xD;&#xA;&#xD;&#xA;listBackgroundColor&#xD;&#xA;Background color for lists. Typically lighter than the backgroundColor&#xD;&#xA;&#xD;&#xA;labelBackgroundColor&#xD;&#xA;Labels typically have no background. There are text on a panel background.&#xD;&#xA;&#xD;&#xA;boxBackgroundColor&#xD;&#xA;Used for a ComboBox. Should this be the same as a list? And/or TextField?&#xD;&#xA;&#xD;&#xA;textFieldBackgroundColor&#xD;&#xA;Background color for TextFields.&#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundColor" eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EColor"
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The default background color. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buttonBackgroundColor"
        eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EColor"
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The background color for buttons."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="panelBackgroundColor" eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EColor"
        defaultValueLiteral="1,2,3" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The (background) color for panels."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listBackgroundColor" eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EColor"
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The background color for lists."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelBackgroundColor" eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EColor"
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The background color for labels."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boxBackgroundColor" eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EColor"
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The background color for combo boxes."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textFieldBackgroundColor"
        eType="ecore:EDataType ../../goedegep.types.model/model/types.ecore#//EColor"
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The background color for text fields and areas."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleLook">
    <eStructuralFeatures xsi:type="ecore:EReference" name="look" lowerBound="1" eType="#//Look"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moduleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourcesClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LookInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleLooks" upperBound="-1"
        eType="#//ModuleLook" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
