module goedegep.travels.app {
  exports goedegep.travels.app;
  exports goedegep.travels.app.logic;
  exports goedegep.travels.app.guifx;
  
  opens goedegep.travels.app.logic;

  requires transitive com.atlis.location.nominatim;
  requires transitive com.gluonhq.maps;
  requires com.google.common.geometry;
  requires de.micromata.opengis.kml.v220;
  requires goedegep.appgen;
  requires transitive goedegep.jfx;
  requires transitive goedegep.geo;
  requires transitive goedegep.model.properties;
  requires transitive goedegep.types.model;
  requires transitive goedegep.travels.model;
  requires goedegep.ov2;
  requires transitive goedegep.poi.app;
  requires goedegep.properties.app;
  requires goedegep.util;
  requires java.desktop;
  requires java.logging;
  requires java.xml;
  requires javafx.base;
  requires javafx.controls;
  requires transitive javafx.graphics;
  requires javafx.swing;
  requires javafx.web;
  requires com.google.common.jimfs;
  requires com.openhtmltopdf;
  requires com.openhtmltopdf.pdfboxout;
  requires org.apache.commons.imaging;
  requires org.apache.commons.io;
  requires org.apache.commons.lang3;
  requires org.commonmark;
  requires org.eclipse.emf.common;
  requires org.eclipse.emf.ecore;
  requires org.apache.pdfbox;
  requires com.google.gson;
  requires transitive goedegep.gpx;
  requires javafx.media;
  requires jdk.jsobject;
  requires transitive goedegep.travels.checklist.model;
  requires goedegep.gpx.model;
  requires goedegep.mapview;
  requires goedegep.resources;
  requires goedegep.myworld.common;
  requires transitive goedegep.gpx.app;
  requires goedegep.gpx10.model;
  requires goedegep.media.mediadb.app;
//  requires goedegep.media.app;
}