package goedegep.media.mediadb.app;

public enum MediaDbAppError {
  ALBUM_IN_MEDIADB_FOUND_MORE_THAN_ONCE_ON_DISC,
  ALBUM_IN_MEDIADB_NOT_FOUND_ON_DISC,
  ALBUM_ON_DISC_NOT_FOUND_IN_MEDIADB,
  NO_MY_INFO_FOR_ALBUM,
  NO_RELEASE_DATE_FOR_ALBUM,
  TRACK_IN_MEDIADB_NOT_FOUND_ON_DISC,
  TRACK_ON_DISC_NOT_FOUND_IN_MEDIADB,
  TRACKS_WITH_DIFFERENT_EXTENSIONS,
  WRONG_NUMBER_OF_TRACKS
}
