package goedegep.media.mediadb.app;

public enum MediaDbError {
  ALBUM_WITHOUT_ARTIST,
  ALBUM_WITHOUT_TITLE,
  ALBUM_WITH_EMPTY_TITLE,
  TRACK_WITHOUT_TITLE,
  BONUS_TRACK_IN_TITLE,
  OBSOLETE_TRACK,
  ARTIST_NOT_REFERRED_TO,
  IWANT_AT_ALBUM_AND_TRACK_LEVEL,
  IHAVEON_AT_ALBUM_AND_TRACK_LEVEL,
  IHAVEON_SAME_FOR_ALL_TRACKS
}
